/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dat240.project.Gruppe2;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) throws IOException {
        ArrayList<File> filer = new ArrayList<>();
        filer = pngreader();
        String filepath = filer.get(2).getPath();
        Image bildet = new Image(1, filepath.replaceAll("\\\\", "/"));
        bildet.generateimage();
    }

    public static ArrayList<File> pngreader(){
        ArrayList<File> filer = new ArrayList<>();
        File imagefolder = new File("task 2 scattered images pc");
        File[] listoffiles = imagefolder.listFiles((dir, name) -> !name.equals(".DS_Store"));    
        for(File folder: listoffiles){
            String filepath = folder.getPath();
            File image = new File(filepath.replaceAll("\\\\", "/"));
            filer.add(image);
        }
        return filer;
    }
}
